"""add completed_at to check_ins

Revision ID: 77028de3a68d
Revises: 7b2f09c0cf37
Create Date: 2025-06-29 04:45:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77028de3a68d'
down_revision: Union[str, None] = '7b2f09c0cf37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check_ins', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('check_ins', 'completed_at')
    # ### end Alembic commands ###
