"""Add call_sid to check_ins

Revision ID: 7b2f09c0cf37
Revises: 
Create Date: 2025-06-29 03:27:14.781261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b2f09c0cf37'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check_ins', sa.Column('call_sid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('check_ins', 'call_sid')
    # ### end Alembic commands ###
