name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: carecall-943219616764
  REGION: us-east1
  BACKEND_SERVICE: carecall-backend
  FRONTEND_SERVICE: carecall-frontend
  INSTANCE_CONNECTION_NAME: carecall-464302:us-east1:carecall-db
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      env:
        DATABASE_URL: sqlite:///./test.db
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      run: |
        cd backend
        pytest

  deploy-backend:
    needs: test-backend
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build and push Docker image
      run: |
        gcloud auth configure-docker
        docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.BACKEND_SERVICE }}:${{ github.sha }} ./backend
        docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.BACKEND_SERVICE }}:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ env.BACKEND_SERVICE }} \
        --image gcr.io/${{ env.PROJECT_ID }}/${{ env.BACKEND_SERVICE }}:${{ github.sha }} \
        --region ${{ env.REGION }} \
        --platform managed \
        --allow-unauthenticated \
        --add-cloudsql-instances ${{ env.INSTANCE_CONNECTION_NAME }} \
        --update-env-vars DATABASE_URL="postgresql+asyncpg://postgres:${{ env.DB_PASSWORD }}@/${{ env.INSTANCE_CONNECTION_NAME }}/carecall?host=/cloudsql/${{ env.INSTANCE_CONNECTION_NAME }}" \
        --update-env-vars JWT_SECRET="${{ secrets.JWT_SECRET }}" \
        --update-env-vars RESEND_API_KEY="${{ secrets.RESEND_API_KEY }}"

  deploy-frontend:
    needs: deploy-backend
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v2

    - name: Install Vercel CLI
      run: npm install --global vercel@latest

    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      run: |
        cd frontend
        vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} 